apiVersion: v1
kind: Namespace
metadata:
  name: restricted
---
apiVersion: v1
kind: Pod
metadata:
  name: lab8server
  namespace: restricted
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: lab8server
  namespace: restricted
spec:
  selector:
    app: lab8server
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: Sleepybox1
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: Sleepybox2
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restricted-policy
  namespace: restricted
spec:
  podSelector:
    matchLabels:
      app: lab8server
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: Sleepybox1
